name: image-push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: pranay921
          password: ${{secrets.DOCKER_TOKEN}}

      - name: docker image build
        run: docker build -t pranay921/myapp:latest .

      - name: docker image push
        run: docker push pranay921/myapp:latest